name: Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup GO environment
      uses: actions/setup-go@v3

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: 5.0

    - name: Setup environment variables
      run: |
        export SECRET_KEY=${SECRET_KEY}
        export ADMIN_USERNAME=${ADMIN_USERNAME}
        export ADMIN_PASSWORD=${ADMIN_PASSWORD}
        export GIN_MODE=${GIN_MODE}
      
    - name: Test handlers with Make
      run: make test
      
